name: "Astuteo"
description: "DESIGNED TO THRIVE"

source: .
destination: _site

url: "http://jskovgaard9.github.io/Astuteo/"
baseurl: "/Astuteo"

paginate: 10

#comment

markdown: rdiscount
permalink: pretty
pygments: true

